mybatis:
  type-aliases-package: cn.booktable.modules.entity # 实体类包的路径
  configuration:
    map-underscore-to-camel-case: true # 将下划线转为驼峰命名
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath*:/mapper/**/*.xml # mapper xml配置文件文件路径
# 打印sql
logging:
  level:
    cn.booktable.modules.dao : debug
# 数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/codework?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: dev
    password: dev123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # druid
    druid:
      initialSize: 10
      filters: stat
      maxActive: 100
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
